name: Build and Push Docker Image (Tag)

on:
  push:
    tags:
      - 'v*'
      - 'V*'
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: do1e/nvidia-smi-web-dashboard

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (optional multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract tag name
        id: vars
        run: |
          REF_NAME="${GITHUB_REF##*/}"
          echo "tag=$REF_NAME" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (tag + latest)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }}
            ${{ env.IMAGE_NAME }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.vars.outputs.tag }}

      - name: Summary
        run: |
          echo "Published $IMAGE_NAME:latest and $IMAGE_NAME:${{ steps.vars.outputs.tag }}" >> $GITHUB_STEP_SUMMARY
